- search:
    provider: brave
    target: _blank
- netdata:
    url: http://host.containers.internal:19999
    node: b-k3s
- datetime:
    format:
      timeStyle: short
      dateStyle: medium
      hourCycle: h23
